export const files = [
    {
        nome: 'Caterina 1',
        imgURL: "assets/thumb_caterina1.jpg",
        vidURL: "assets/videos/video_caterina1.mp4",
        descriptType: 'Esquete Internet',
        descripTitle: 'Medo',
        descripClient: 'Luciana Castellano',
    },
    {
        nome: 'São Bercirco',
        imgURL: "assets/thumb_sbcirco.jpg",
        vidURL: "assets/videos/video_sbcirco.mp4",
        descriptType: 'Color Grading',
        descripTitle: 'São Bercirco',
        descripClient: 'dir. Mariana França',
    },   
    {
        nome: 'Letícia',
        imgURL: "assets/thumb_leticia.jpg",
        vidURL: "assets/videos/video_leticia.mp4",
        descriptType: 'Promocional',
        descripTitle: 'Fisioterapia',
        descripClient: 'Letícia Mello',
    },   
    {
        nome: 'Square',
        imgURL: "assets/thumb_square.jpg",
        vidURL: "assets/videos/video_square.mp4",
        descriptType: 'Promocional',
        descripTitle: 'Infraestrutura',
        descripClient: 'Square - Soluções em Tecnologia',
    },   
    {
        nome: 'Caterina 2',
        imgURL: "assets/thumb_caterina2.jpg",
        vidURL: "assets/videos/video_caterina2.mp4",
        descriptType: 'Esquete Internet',
        descripTitle: 'É Importante Errar',
        descripClient: 'Luciana Castellano',
    },   
    {
        nome: 'Paineiras',
        imgURL: "assets/thumb_paineiras.jpg",
        vidURL: "assets/videos/video_paineiras.mp4",
        descriptType: 'Mosaico Musical',
        descripTitle: 'Um Canto para as Mães',
        descripClient: 'Luciana Castellano',
    },   
    {
        nome: 'Mediotec',
        imgURL: "assets/thumb_mediotec.jpg",
        vidURL: "assets/videos/video_mediotec.mp4",
        descriptType: 'Produção Musical Completa',
        descripTitle: 'Dunas',
        descripClient: 'MEDIOTEC Música',
    },   
    {
        nome: 'Saraf',
        imgURL: "assets/thumb_saraf.jpg",
        vidURL: "assets/videos/video_saraf.mp4",
        descriptType: 'Conteúdo',
        descripTitle: 'Inventário de Ativos',
        descripClient: 'SARAF Controle Patrimonial',
    },   
    {
        nome: 'Xô Aluguel Online',
        imgURL: "assets/thumb_xoaluguel.jpg",
        vidURL: "assets/videos/video_xoaluguel.mp4",
        descriptType: 'Vídeo de Vendas',
        descripTitle: 'Xô Aluguel Online',
        descripClient: 'ANDUMA Empreendimentos Imobiliários',
    },   
    {
        nome: 'Série',
        imgURL: "assets/thumb_serie.jpg",
        vidURL: "assets/videos/video_serie.mp4",
        descriptType: 'Mini Web Série',
        descripTitle: 'Mafalda - Ep. 01',
        descripClient: 'Caminhos Potentes',
    },   
]